import { ProgressionTierId } from "./ProgressionConfig";

export type AchievementCondition =
  | { type: "totalOranges"; value: string }
  | { type: "totalTaps"; value: number }
  | { type: "upgradeLevel"; id: string; level: number }
  | { type: "generatorLevel"; id: string; level: number }
  | { type: "totalUpgradeLevels"; value: number }
  | { type: "totalGeneratorLevels"; value: number }
  | { type: "eps"; value: string }
  | { type: "goldenLeaf"; value: string }
  | { type: "prestiges"; value: number }
  | { type: "adBoostActive" }
  | { type: "purchasedProducts"; value: number };

export type AchievementConfigItem = {
  id: string;
  name: string;
  description: string;
  tier: ProgressionTierId;
  icon: string;
  condition: AchievementCondition;
  rewardText: string;
  toast: string;
  collectionLine: string;
};

export const AchievementConfig = {
  achievements: [
    {
      id: "first_orange",
      name: "첫 귤 인사",
      description: "첫 귤을 카피바라에게 건넵니다.",
      tier: "yard",
      icon: "orange",
      condition: { type: "totalTaps", value: 1 },
      rewardText: "정원 앨범 첫 장",
      toast: "첫 귤이 정원 앨범에 붙었어요.",
      collectionLine: "모모가 첫 귤 냄새를 기억합니다.",
    },
    {
      id: "ten_taps",
      name: "손끝 예열",
      description: "카피바라를 10번 터치합니다.",
      tier: "yard",
      icon: "tap",
      condition: { type: "totalTaps", value: 10 },
      rewardText: "터치 루틴 기록",
      toast: "손끝 리듬이 생겼어요.",
      collectionLine: "짧은 터치가 귤빛 루틴이 됩니다.",
    },
    {
      id: "hundred_taps",
      name: "마당 단골",
      description: "카피바라를 100번 터치합니다.",
      tier: "yard",
      icon: "tap_100",
      condition: { type: "totalTaps", value: 100 },
      rewardText: "단골 집사 배지",
      toast: "카피바라들이 집사의 손길을 알아봅니다.",
      collectionLine: "마당에 익숙한 발자국이 남았습니다.",
    },
    {
      id: "thousand_taps",
      name: "귤 박자 장인",
      description: "카피바라를 1,000번 터치합니다.",
      tier: "storehouse",
      icon: "tap_1000",
      condition: { type: "totalTaps", value: 1000 },
      rewardText: "박자 장인 스티커",
      toast: "터치 박자가 창고까지 울립니다.",
      collectionLine: "나린이 박자표를 창고 벽에 붙였습니다.",
    },
    {
      id: "first_100_oranges",
      name: "작은 바구니",
      description: "누적 100귤을 모읍니다.",
      tier: "yard",
      icon: "basket",
      condition: { type: "totalOranges", value: "100" },
      rewardText: "마당 바구니 기록",
      toast: "첫 바구니가 채워졌어요.",
      collectionLine: "작은 바구니도 충분히 기쁜 시작입니다.",
    },
    {
      id: "first_1k_oranges",
      name: "천 귤 마당",
      description: "누적 1,000귤을 모읍니다.",
      tier: "yard",
      icon: "orange_1k",
      condition: { type: "totalOranges", value: "1000" },
      rewardText: "천 귤 표지판",
      toast: "마당에 천 귤 표지판이 섰어요.",
      collectionLine: "모모가 표지판 옆에서 낮잠을 잡니다.",
    },
    {
      id: "storehouse_5k",
      name: "창고 열쇠",
      description: "누적 5,000귤을 모읍니다.",
      tier: "storehouse",
      icon: "key",
      condition: { type: "totalOranges", value: "5000" },
      rewardText: "귤 창고 입장",
      toast: "귤 창고 열쇠를 받았어요.",
      collectionLine: "창고 문틈으로 향이 먼저 나옵니다.",
    },
    {
      id: "fragrant_25k",
      name: "향기로운 선반",
      description: "누적 25,000귤을 모읍니다.",
      tier: "storehouse",
      icon: "shelf",
      condition: { type: "totalOranges", value: "25000" },
      rewardText: "향기 선반 명패",
      toast: "향기로운 선반이 정리됐어요.",
      collectionLine: "나린이 상자마다 작은 이름표를 붙였습니다.",
    },
    {
      id: "onsen_75k",
      name: "온천 김",
      description: "누적 75,000귤을 모읍니다.",
      tier: "onsen",
      icon: "steam",
      condition: { type: "totalOranges", value: "75000" },
      rewardText: "온천 초대장",
      toast: "따뜻한 온천 김이 피어올라요.",
      collectionLine: "다미가 쉬는 시간 안내판을 세웠습니다.",
    },
    {
      id: "onsen_300k",
      name: "따뜻한 오후",
      description: "누적 300,000귤을 모읍니다.",
      tier: "onsen",
      icon: "afternoon",
      condition: { type: "totalOranges", value: "300000" },
      rewardText: "온천 오후 배지",
      toast: "정원에 따뜻한 오후가 찾아왔어요.",
      collectionLine: "온천 물결이 생산 리듬을 부드럽게 만듭니다.",
    },
    {
      id: "bamboo_1m",
      name: "백만 귤 정원",
      description: "누적 1,000,000귤을 모읍니다.",
      tier: "bamboo_garden",
      icon: "home",
      condition: { type: "totalOranges", value: "1000000" },
      rewardText: "백만 귤 간판",
      toast: "백만 귤 정원이 열렸어요.",
      collectionLine: "비로가 대나무 길에 새 간판을 세웠습니다.",
    },
    {
      id: "bamboo_5m",
      name: "대나무 운반망",
      description: "누적 5,000,000귤을 모읍니다.",
      tier: "bamboo_garden",
      icon: "bamboo",
      condition: { type: "totalOranges", value: "5000000" },
      rewardText: "운반망 지도",
      toast: "대나무 운반망이 연결됐어요.",
      collectionLine: "수레가 정원을 더 넓게 돌기 시작합니다.",
    },
    {
      id: "golden_25m",
      name: "황금 숲 입구",
      description: "누적 25,000,000귤을 모읍니다.",
      tier: "golden_forest",
      icon: "gold_path",
      condition: { type: "totalOranges", value: "25000000" },
      rewardText: "황금 숲 표식",
      toast: "황금 숲 입구가 반짝입니다.",
      collectionLine: "하늘이 첫 황금잎을 조용히 주웠습니다.",
    },
    {
      id: "soft_paw_1",
      name: "말랑 첫걸음",
      description: "말랑 앞발을 1레벨로 만듭니다.",
      tier: "yard",
      icon: "paw",
      condition: { type: "upgradeLevel", id: "soft_paw", level: 1 },
      rewardText: "앞발 도장",
      toast: "말랑 앞발 도장이 찍혔어요.",
      collectionLine: "작은 앞발 자국이 마당에 남았습니다.",
    },
    {
      id: "soft_paw_10",
      name: "앞발 숙련",
      description: "말랑 앞발을 10레벨로 만듭니다.",
      tier: "yard",
      icon: "paw_10",
      condition: { type: "upgradeLevel", id: "soft_paw", level: 10 },
      rewardText: "숙련 앞발 도장",
      toast: "앞발 터치가 확실히 부드러워졌어요.",
      collectionLine: "모모가 앞발 도장을 자랑합니다.",
    },
    {
      id: "basket_1",
      name: "첫 자동 바구니",
      description: "귤 바구니를 1레벨로 만듭니다.",
      tier: "yard",
      icon: "basket_1",
      condition: { type: "generatorLevel", id: "orange_basket", level: 1 },
      rewardText: "첫 자동 생산 기록",
      toast: "귤 바구니가 일을 시작했어요.",
      collectionLine: "바구니가 비어 있는 시간이 줄었습니다.",
    },
    {
      id: "basket_25",
      name: "바구니 행렬",
      description: "귤 바구니를 25레벨로 만듭니다.",
      tier: "storehouse",
      icon: "basket_25",
      condition: { type: "generatorLevel", id: "orange_basket", level: 25 },
      rewardText: "바구니 행렬 사진",
      toast: "귤 바구니가 줄지어 움직입니다.",
      collectionLine: "마당에서 창고까지 바구니 길이 생겼습니다.",
    },
    {
      id: "storehouse_first",
      name: "상자 정리 시작",
      description: "나무 상자 줄을 1레벨로 만듭니다.",
      tier: "storehouse",
      icon: "crate",
      condition: { type: "generatorLevel", id: "wooden_crate_line", level: 1 },
      rewardText: "첫 상자 번호표",
      toast: "나무 상자가 정렬됐어요.",
      collectionLine: "나린이 첫 번호표를 붙였습니다.",
    },
    {
      id: "onsen_first",
      name: "첫 온천 손님",
      description: "따뜻한 온천을 1레벨로 만듭니다.",
      tier: "onsen",
      icon: "pond",
      condition: { type: "generatorLevel", id: "warm_pond", level: 1 },
      rewardText: "온천 손님 명부",
      toast: "첫 온천 손님이 도착했어요.",
      collectionLine: "다미가 수건을 하나 더 준비했습니다.",
    },
    {
      id: "bamboo_cart_first",
      name: "대나무 첫 운행",
      description: "대나무 카트를 1레벨로 만듭니다.",
      tier: "bamboo_garden",
      icon: "bamboo_cart",
      condition: { type: "generatorLevel", id: "bamboo_cart", level: 1 },
      rewardText: "첫 운행표",
      toast: "대나무 카트가 첫 운행을 마쳤어요.",
      collectionLine: "비로가 수레 바퀴를 닦았습니다.",
    },
    {
      id: "toolbox_first",
      name: "도구함 개방",
      description: "집사 도구함을 1레벨로 만듭니다.",
      tier: "bamboo_garden",
      icon: "toolbox",
      condition: { type: "generatorLevel", id: "butler_toolbox", level: 1 },
      rewardText: "정비 도구 목록",
      toast: "집사 도구함이 열렸어요.",
      collectionLine: "정원 도구들이 제자리를 찾았습니다.",
    },
    {
      id: "gold_path_first",
      name: "황금 숲 첫길",
      description: "황금 숲길을 1레벨로 만듭니다.",
      tier: "golden_forest",
      icon: "gold_path",
      condition: { type: "generatorLevel", id: "golden_forest_path", level: 1 },
      rewardText: "황금 숲길 조각",
      toast: "황금 숲길이 첫 발자국을 받았어요.",
      collectionLine: "하늘이 길 위의 잎새를 정리합니다.",
    },
    {
      id: "tap_suite_20",
      name: "손맛 세트",
      description: "터치 업그레이드 총 레벨 20을 달성합니다.",
      tier: "storehouse",
      icon: "tap_suite",
      condition: { type: "totalUpgradeLevels", value: 20 },
      rewardText: "손맛 세트 카드",
      toast: "터치 업그레이드 세트가 완성됐어요.",
      collectionLine: "손으로 모으는 귤도 당당한 생산 라인입니다.",
    },
    {
      id: "tap_suite_100",
      name: "집사 손끝",
      description: "터치 업그레이드 총 레벨 100을 달성합니다.",
      tier: "bamboo_garden",
      icon: "butler_hand",
      condition: { type: "totalUpgradeLevels", value: 100 },
      rewardText: "집사 손끝 배지",
      toast: "집사 손끝이 정원의 리듬이 됐어요.",
      collectionLine: "카피바라들이 터치 박자를 따라 움직입니다.",
    },
    {
      id: "generator_suite_20",
      name: "시설 세트",
      description: "자동 생산 시설 총 레벨 20을 달성합니다.",
      tier: "storehouse",
      icon: "facility_suite",
      condition: { type: "totalGeneratorLevels", value: 20 },
      rewardText: "시설 세트 카드",
      toast: "자동 생산 시설 세트가 꾸려졌어요.",
      collectionLine: "정원이 혼자서도 천천히 굴러가기 시작합니다.",
    },
    {
      id: "generator_suite_120",
      name: "정원 운영표",
      description: "자동 생산 시설 총 레벨 120을 달성합니다.",
      tier: "bamboo_garden",
      icon: "schedule",
      condition: { type: "totalGeneratorLevels", value: 120 },
      rewardText: "정원 운영표",
      toast: "정원 운영표가 꽉 찼어요.",
      collectionLine: "시설마다 맡은 일이 선명해졌습니다.",
    },
    {
      id: "eps_10",
      name: "초당 열 귤",
      description: "초당 10귤 생산에 도달합니다.",
      tier: "yard",
      icon: "eps_10",
      condition: { type: "eps", value: "10" },
      rewardText: "작은 생산표",
      toast: "초당 10귤 생산에 도달했어요.",
      collectionLine: "숫자가 천천히, 하지만 확실히 흐릅니다.",
    },
    {
      id: "eps_1k",
      name: "천 귤 흐름",
      description: "초당 1,000귤 생산에 도달합니다.",
      tier: "onsen",
      icon: "eps_1k",
      condition: { type: "eps", value: "1000" },
      rewardText: "중반 생산표",
      toast: "초당 1,000귤 흐름이 열렸어요.",
      collectionLine: "온천의 김 사이로 숫자가 빠르게 오릅니다.",
    },
    {
      id: "eps_100k",
      name: "대나무 급류",
      description: "초당 100,000귤 생산에 도달합니다.",
      tier: "bamboo_garden",
      icon: "eps_100k",
      condition: { type: "eps", value: "100000" },
      rewardText: "후반 생산표",
      toast: "초당 100,000귤 급류가 생겼어요.",
      collectionLine: "대나무 길의 수레가 쉬지 않고 움직입니다.",
    },
    {
      id: "eps_1m",
      name: "백만 귤 물결",
      description: "초당 1,000,000귤 생산에 도달합니다.",
      tier: "golden_forest",
      icon: "eps_1m",
      condition: { type: "eps", value: "1000000" },
      rewardText: "황금 생산표",
      toast: "초당 백만 귤 물결이 반짝입니다.",
      collectionLine: "황금 숲의 길마다 귤빛이 흐릅니다.",
    },
    {
      id: "first_leaf",
      name: "첫 황금 나뭇잎",
      description: "황금 나뭇잎 1개를 얻습니다.",
      tier: "golden_forest",
      icon: "leaf",
      condition: { type: "goldenLeaf", value: "1" },
      rewardText: "첫 황금잎 표본",
      toast: "첫 황금 나뭇잎이 앨범에 꽂혔어요.",
      collectionLine: "환생의 기억이 작은 잎으로 남았습니다.",
    },
    {
      id: "five_leaf",
      name: "다섯 잎새",
      description: "황금 나뭇잎 5개를 보유합니다.",
      tier: "golden_forest",
      icon: "leaf_5",
      condition: { type: "goldenLeaf", value: "5" },
      rewardText: "다섯 잎새 묶음",
      toast: "황금 나뭇잎 다섯 장이 모였어요.",
      collectionLine: "하늘이 잎새를 작은 끈으로 묶었습니다.",
    },
    {
      id: "first_prestige",
      name: "첫 계절 넘김",
      description: "환생을 1회 진행합니다.",
      tier: "golden_forest",
      icon: "prestige",
      condition: { type: "prestiges", value: 1 },
      rewardText: "첫 계절 기록",
      toast: "첫 계절을 황금잎으로 넘겼어요.",
      collectionLine: "정원은 끝나지 않고 다음 계절로 접힙니다.",
    },
    {
      id: "third_prestige",
      name: "세 번째 계절",
      description: "환생을 3회 진행합니다.",
      tier: "golden_forest",
      icon: "prestige_3",
      condition: { type: "prestiges", value: 3 },
      rewardText: "세 계절 기록",
      toast: "세 번째 계절의 문이 열렸어요.",
      collectionLine: "계절 기억문이 더 밝게 빛납니다.",
    },
    {
      id: "ad_festival",
      name: "수확 축제 시작",
      description: "귤 수확 축제를 한 번 시작합니다.",
      tier: "yard",
      icon: "festival",
      condition: { type: "adBoostActive" },
      rewardText: "축제 리본",
      toast: "수확 축제 리본이 걸렸어요.",
      collectionLine: "루루가 작은 깃발을 흔듭니다.",
    },
    {
      id: "sandbox_gift",
      name: "특별 상자 확인",
      description: "샌드박스 상품 보상을 1회 수령합니다.",
      tier: "storehouse",
      icon: "gift",
      condition: { type: "purchasedProducts", value: 1 },
      rewardText: "특별 상자 스티커",
      toast: "특별 상자 스티커가 붙었어요.",
      collectionLine: "실제 결제가 아닌 샌드박스 보상 기록입니다.",
    },
    {
      id: "sandbox_shelf",
      name: "상점 선반 점검",
      description: "샌드박스 상품 보상을 2종 이상 수령합니다.",
      tier: "storehouse",
      icon: "gift",
      condition: { type: "purchasedProducts", value: 2 },
      rewardText: "상점 점검표",
      toast: "상점 선반 점검표가 채워졌어요.",
      collectionLine: "출시 전 상품 흐름을 안전하게 확인했습니다.",
    },
    {
      id: "all_yard_core",
      name: "마당 기본 세트",
      description: "낮잠 평상과 작은 물길을 1레벨 이상으로 만듭니다.",
      tier: "yard",
      icon: "yard_set",
      condition: { type: "generatorLevel", id: "tiny_watering_path", level: 1 },
      rewardText: "마당 세트 사진",
      toast: "마당 기본 세트가 완성됐어요.",
      collectionLine: "물길과 평상이 마당의 리듬을 만들었습니다.",
    },
    {
      id: "late_game_marker",
      name: "기억문 앞에서",
      description: "계절 기억문을 1레벨로 만듭니다.",
      tier: "golden_forest",
      icon: "memory_gate",
      condition: { type: "generatorLevel", id: "season_memory_gate", level: 1 },
      rewardText: "기억문 표식",
      toast: "계절 기억문이 조용히 열렸어요.",
      collectionLine: "지난 모든 귤빛이 문 안에서 반짝입니다.",
    },
    {
      id: "memory_touch_first",
      name: "기억 손길",
      description: "기억의 집사술을 1레벨로 만듭니다.",
      tier: "golden_forest",
      icon: "memory",
      condition: { type: "upgradeLevel", id: "memory_butler", level: 1 },
      rewardText: "기억 손길 기록",
      toast: "기억의 손길이 첫 귤을 건넸어요.",
      collectionLine: "지난 계절의 집사 노트가 다시 펼쳐졌습니다.",
    },
  ],
} as const satisfies { achievements: AchievementConfigItem[] };

export type AchievementId = (typeof AchievementConfig.achievements)[number]["id"];
