export const AssetConfig = {
  "capybara.main": "asset:mascot-default",
  "capybara.happy": "css:mascot-happy",
  "capybara.sleepy": "css:mascot-sleepy",
  "capybara.eating": "css:mascot-eating",
  "capybara.celebrate": "css:mascot-celebrate",
  "currency.orange": "asset:orange",
  "currency.goldenLeaf": "asset:leaf",
  "facility.basket": "css:icon-basket",
  "facility.onsen": "css:icon-pond",
  "facility.bamboo": "css:icon-bamboo",
  "facility.goldenForest": "css:icon-gold_path",
  "app.iconDraft": "asset:app-icon-rc2",
  "app.splashDraft": "asset:splash-rc2",
  "effect.sparkle": "css:effect-sparkle",
} as const;
