import { ProgressionTierId } from "./ProgressionConfig";

export type UnlockRequirement =
  | { type: "none" }
  | { type: "lifetimeOranges"; value: string }
  | { type: "goldenLeaf"; value: string }
  | { type: "prestiges"; value: number }
  | { type: "generatorLevel"; id: string; level: number };

type SharedUpgradeConfig = {
  id: string;
  name: string;
  description: string;
  tier: ProgressionTierId;
  icon: string;
  baseCost: string;
  growthRate: number;
  maxLevel: number | null;
  unlock: UnlockRequirement;
  unlockLabel: string;
  uiCopy: string;
};

export type TapUpgradeConfig = SharedUpgradeConfig & {
  tapMultiplierPerLevel: number;
};

export type GeneratorConfig = SharedUpgradeConfig & {
  baseEps: string;
  generatorMultiplier: number;
};

export const BalanceConfig = {
  tapUpgrades: [
    {
      id: "soft_paw",
      name: "말랑 앞발",
      description: "카피바라가 귤을 더 정확히 받아요.",
      tier: "yard",
      icon: "paw",
      baseCost: "15",
      growthRate: 1.15,
      tapMultiplierPerLevel: 1,
      maxLevel: null,
      unlock: { type: "none" },
      unlockLabel: "처음부터 사용 가능",
      uiCopy: "터치 성장을 시작하는 기본 손맛입니다.",
    },
    {
      id: "butler_gloves",
      name: "집사 장갑",
      description: "폭신한 장갑으로 전달량을 키워요.",
      tier: "yard",
      icon: "glove",
      baseCost: "120",
      growthRate: 1.22,
      tapMultiplierPerLevel: 4,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "100" },
      unlockLabel: "누적 100귤",
      uiCopy: "초반 터치 효율을 빠르게 끌어올립니다.",
    },
    {
      id: "orange_spoon",
      name: "귤 스푼",
      description: "작은 귤조각까지 흘리지 않게 떠서 카피바라에게 건넵니다.",
      tier: "yard",
      icon: "spoon",
      baseCost: "950",
      growthRate: 1.24,
      tapMultiplierPerLevel: 12,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "1000" },
      unlockLabel: "누적 1,000귤",
      uiCopy: "손으로 모으는 구간의 속도를 확실히 올립니다.",
    },
    {
      id: "sorting_rhythm",
      name: "분류 리듬",
      description: "창고 박자에 맞춰 귤을 주면 카피바라들이 더 빠르게 반응합니다.",
      tier: "storehouse",
      icon: "metronome",
      baseCost: "6200",
      growthRate: 1.26,
      tapMultiplierPerLevel: 36,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "5000" },
      unlockLabel: "귤 창고 해금",
      uiCopy: "창고 구간에서 터치가 생산 시설과 함께 굴러갑니다.",
    },
    {
      id: "warm_towel",
      name: "온천 수건",
      description: "따뜻한 수건으로 카피바라가 귤을 더 기분 좋게 받아요.",
      tier: "onsen",
      icon: "towel",
      baseCost: "52000",
      growthRate: 1.27,
      tapMultiplierPerLevel: 120,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "25000" },
      unlockLabel: "누적 25,000귤",
      uiCopy: "온천 전환 전후의 터치 보상을 받쳐 줍니다.",
    },
    {
      id: "citrus_recipe",
      name: "귤 간식 레시피",
      description: "귤을 간식으로 다듬어 한 번의 터치에 더 큰 만족을 줍니다.",
      tier: "onsen",
      icon: "recipe",
      baseCost: "180000",
      growthRate: 1.29,
      tapMultiplierPerLevel: 360,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "75000" },
      unlockLabel: "온천 구역 해금",
      uiCopy: "중반 터치 보상이 뒤처지지 않게 잡아 줍니다.",
    },
    {
      id: "bamboo_touch",
      name: "대나무 손길",
      description: "대나무 길을 따라 귤을 건네며 운반 동선을 줄입니다.",
      tier: "bamboo_garden",
      icon: "bamboo",
      baseCost: "950000",
      growthRate: 1.31,
      tapMultiplierPerLevel: 1100,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "400000" },
      unlockLabel: "누적 400,000귤",
      uiCopy: "대나무 정원 진입 전 터치 폭발력을 준비합니다.",
    },
    {
      id: "festival_clap",
      name: "축제 박수",
      description: "귤 수확 축제의 박자에 맞춰 카피바라들이 신나게 모입니다.",
      tier: "bamboo_garden",
      icon: "clap",
      baseCost: "3600000",
      growthRate: 1.33,
      tapMultiplierPerLevel: 3600,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "1200000" },
      unlockLabel: "대나무 정원 해금",
      uiCopy: "환생 전 마지막 수동 성장 구간을 밀어 줍니다.",
    },
    {
      id: "golden_leaf_polish",
      name: "황금잎 손질",
      description: "황금 나뭇잎을 손질해 다음 귤 전달에 지난 정원의 힘을 더합니다.",
      tier: "golden_forest",
      icon: "leaf_polish",
      baseCost: "14000000",
      growthRate: 1.35,
      tapMultiplierPerLevel: 12000,
      maxLevel: null,
      unlock: { type: "goldenLeaf", value: "1" },
      unlockLabel: "황금 나뭇잎 1개",
      uiCopy: "첫 환생 이후 터치 보상을 다시 의미 있게 만듭니다.",
    },
    {
      id: "memory_butler",
      name: "기억의 집사술",
      description: "이전 계절의 돌봄 기록을 되살려 한 번의 터치를 묵직하게 만듭니다.",
      tier: "golden_forest",
      icon: "memory",
      baseCost: "58000000",
      growthRate: 1.38,
      tapMultiplierPerLevel: 42000,
      maxLevel: null,
      unlock: { type: "prestiges", value: 2 },
      unlockLabel: "환생 2회",
      uiCopy: "반복 환생 이후에도 수동 플레이의 존재감을 유지합니다.",
    },
  ],
  generators: [
    {
      id: "orange_basket",
      name: "귤 바구니",
      description: "카피바라가 천천히 귤을 모아 담습니다.",
      tier: "yard",
      icon: "basket",
      baseCost: "25",
      growthRate: 1.18,
      baseEps: "0.2",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "none" },
      unlockLabel: "처음부터 사용 가능",
      uiCopy: "첫 자동 생산을 시작합니다.",
    },
    {
      id: "nap_mat",
      name: "낮잠 평상",
      description: "짧게 쉬는 카피바라들이 깨어날 때마다 귤을 하나씩 챙깁니다.",
      tier: "yard",
      icon: "mat",
      baseCost: "85",
      growthRate: 1.19,
      baseEps: "0.7",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "80" },
      unlockLabel: "누적 80귤",
      uiCopy: "초반 idle 수익을 부드럽게 올립니다.",
    },
    {
      id: "shade_parasol",
      name: "그늘 파라솔",
      description: "햇볕을 피해 쉬는 자리마다 작은 귤 접시가 놓입니다.",
      tier: "yard",
      icon: "parasol",
      baseCost: "320",
      growthRate: 1.2,
      baseEps: "2.2",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "300" },
      unlockLabel: "누적 300귤",
      uiCopy: "마당의 안정적인 두 번째 생산 라인입니다.",
    },
    {
      id: "tiny_watering_path",
      name: "작은 물길",
      description: "물길 옆 귤나무가 천천히 열매를 맺습니다.",
      tier: "yard",
      icon: "water_path",
      baseCost: "1200",
      growthRate: 1.21,
      baseEps: "6.5",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "1000" },
      unlockLabel: "누적 1,000귤",
      uiCopy: "마당에서 창고로 넘어갈 발판을 만듭니다.",
    },
    {
      id: "wooden_crate_line",
      name: "나무 상자 줄",
      description: "귤 상자를 줄 맞춰 세워 운반 대기 시간을 줄입니다.",
      tier: "storehouse",
      icon: "crate",
      baseCost: "5200",
      growthRate: 1.22,
      baseEps: "18",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "5000" },
      unlockLabel: "귤 창고 해금",
      uiCopy: "창고 구간의 첫 생산 시설입니다.",
    },
    {
      id: "fragrance_storehouse",
      name: "향기 창고",
      description: "향이 진한 귤을 따로 보관해 카피바라들이 더 자주 찾아옵니다.",
      tier: "storehouse",
      icon: "storehouse",
      baseCost: "14000",
      growthRate: 1.23,
      baseEps: "46",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "12000" },
      unlockLabel: "누적 12,000귤",
      uiCopy: "창고 수익의 중심 시설입니다.",
    },
    {
      id: "sorting_table",
      name: "귤 분류대",
      description: "크기별로 나눈 귤이 다음 작업 속도를 빠르게 만듭니다.",
      tier: "storehouse",
      icon: "table",
      baseCost: "30000",
      growthRate: 1.24,
      baseEps: "92",
      generatorMultiplier: 1.02,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "25000" },
      unlockLabel: "누적 25,000귤",
      uiCopy: "생산과 전체 효율을 동시에 조금씩 올립니다.",
    },
    {
      id: "cart_stop",
      name: "수레 정류장",
      description: "수레가 멈추는 자리를 정해 창고 왕복 시간을 줄입니다.",
      tier: "storehouse",
      icon: "cart_stop",
      baseCost: "62000",
      growthRate: 1.245,
      baseEps: "180",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "45000" },
      unlockLabel: "누적 45,000귤",
      uiCopy: "온천 구간 전 생산을 끌어올립니다.",
    },
    {
      id: "warm_pond",
      name: "따뜻한 온천",
      description: "쉬는 카피바라들이 몸을 데우고 다시 귤을 모읍니다.",
      tier: "onsen",
      icon: "pond",
      baseCost: "150000",
      growthRate: 1.25,
      baseEps: "420",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "75000" },
      unlockLabel: "온천 구역 해금",
      uiCopy: "중반 생산량을 새 단계로 올립니다.",
    },
    {
      id: "steam_towel_rack",
      name: "김나는 수건걸이",
      description: "수건이 따뜻할수록 카피바라들의 휴식 회전율이 좋아집니다.",
      tier: "onsen",
      icon: "steam_towel",
      baseCost: "310000",
      growthRate: 1.255,
      baseEps: "880",
      generatorMultiplier: 1.03,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "150000" },
      unlockLabel: "누적 150,000귤",
      uiCopy: "온천 시설 전체의 템포를 보강합니다.",
    },
    {
      id: "snack_counter",
      name: "귤 간식대",
      description: "작은 간식 접시가 휴식 후 복귀를 즐겁게 만듭니다.",
      tier: "onsen",
      icon: "snack",
      baseCost: "650000",
      growthRate: 1.265,
      baseEps: "1900",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "300000" },
      unlockLabel: "누적 300,000귤",
      uiCopy: "온천에서 대나무 정원으로 가는 추진력입니다.",
    },
    {
      id: "mineral_stream",
      name: "미네랄 물줄기",
      description: "물줄기 옆 귤나무가 더 단단한 열매를 맺습니다.",
      tier: "onsen",
      icon: "stream",
      baseCost: "1300000",
      growthRate: 1.27,
      baseEps: "4100",
      generatorMultiplier: 1.04,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "600000" },
      unlockLabel: "누적 600,000귤",
      uiCopy: "환생 전 생산 배율의 첫 체감을 만듭니다.",
    },
    {
      id: "bamboo_cart",
      name: "대나무 카트",
      description: "대나무 카트가 귤 상자를 빠르게 나릅니다.",
      tier: "bamboo_garden",
      icon: "bamboo_cart",
      baseCost: "2800000",
      growthRate: 1.275,
      baseEps: "9200",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "1200000" },
      unlockLabel: "대나무 정원 해금",
      uiCopy: "대나무 구간의 대표 운반 시설입니다.",
    },
    {
      id: "wind_chime_bridge",
      name: "바람종 다리",
      description: "바람종 소리가 운반 동선을 알려 길을 잃지 않게 합니다.",
      tier: "bamboo_garden",
      icon: "chime",
      baseCost: "6200000",
      growthRate: 1.285,
      baseEps: "21000",
      generatorMultiplier: 1.04,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "2200000" },
      unlockLabel: "누적 2,200,000귤",
      uiCopy: "운반 시설 효율과 생산량을 함께 올립니다.",
    },
    {
      id: "orange_lantern_road",
      name: "귤 등불길",
      description: "저녁에도 등불을 따라 귤 상자를 옮길 수 있습니다.",
      tier: "bamboo_garden",
      icon: "lantern",
      baseCost: "12000000",
      growthRate: 1.295,
      baseEps: "48000",
      generatorMultiplier: 1,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "4000000" },
      unlockLabel: "누적 4,000,000귤",
      uiCopy: "후반 진입 전 야간 생산을 엽니다.",
    },
    {
      id: "butler_toolbox",
      name: "집사 도구함",
      description: "정원 도구를 정비해 모든 자동 생산 시설 효율이 좋아집니다.",
      tier: "bamboo_garden",
      icon: "toolbox",
      baseCost: "24000000",
      growthRate: 1.305,
      baseEps: "98000",
      generatorMultiplier: 1.08,
      maxLevel: null,
      unlock: { type: "lifetimeOranges", value: "7500000" },
      unlockLabel: "누적 7,500,000귤",
      uiCopy: "전체 자동 생산을 크게 밀어 주는 핵심 배율 시설입니다.",
    },
    {
      id: "golden_forest_path",
      name: "황금 숲길",
      description: "황금 나뭇잎이 떨어진 길마다 귤나무가 다시 자랍니다.",
      tier: "golden_forest",
      icon: "gold_path",
      baseCost: "78000000",
      growthRate: 1.315,
      baseEps: "260000",
      generatorMultiplier: 1.06,
      maxLevel: null,
      unlock: { type: "goldenLeaf", value: "1" },
      unlockLabel: "황금 나뭇잎 1개",
      uiCopy: "환생 후 자동 생산을 다시 빠르게 회복합니다.",
    },
    {
      id: "leaf_compost_house",
      name: "잎새 퇴비장",
      description: "지난 계절의 잎새가 다음 귤나무의 뿌리를 튼튼하게 만듭니다.",
      tier: "golden_forest",
      icon: "compost",
      baseCost: "180000000",
      growthRate: 1.325,
      baseEps: "720000",
      generatorMultiplier: 1.08,
      maxLevel: null,
      unlock: { type: "goldenLeaf", value: "3" },
      unlockLabel: "황금 나뭇잎 3개",
      uiCopy: "반복 환생의 보상을 생산 배율로 전환합니다.",
    },
    {
      id: "moon_orange_observatory",
      name: "달귤 관측소",
      description: "달빛이 좋은 밤을 골라 수확 계획을 세웁니다.",
      tier: "golden_forest",
      icon: "observatory",
      baseCost: "420000000",
      growthRate: 1.34,
      baseEps: "1900000",
      generatorMultiplier: 1.1,
      maxLevel: null,
      unlock: { type: "prestiges", value: 2 },
      unlockLabel: "환생 2회",
      uiCopy: "후반 성장 속도를 장기적으로 안정화합니다.",
    },
    {
      id: "season_memory_gate",
      name: "계절 기억문",
      description: "모든 계절의 정원 기록이 문을 지나며 다음 수확으로 이어집니다.",
      tier: "golden_forest",
      icon: "memory_gate",
      baseCost: "980000000",
      growthRate: 1.36,
      baseEps: "5200000",
      generatorMultiplier: 1.12,
      maxLevel: null,
      unlock: { type: "prestiges", value: 3 },
      unlockLabel: "환생 3회",
      uiCopy: "현재 RC에서 가장 긴 목표가 되는 최종 시설입니다.",
    },
  ],
  global: {
    baseMultiplier: 1,
  },
} as const satisfies {
  tapUpgrades: TapUpgradeConfig[];
  generators: GeneratorConfig[];
  global: { baseMultiplier: number };
};

export type TapUpgradeId = (typeof BalanceConfig.tapUpgrades)[number]["id"];
export type GeneratorId = (typeof BalanceConfig.generators)[number]["id"];
export type UpgradeId = TapUpgradeId | GeneratorId;
