import { ProgressionTierId } from "./ProgressionConfig";

export type DecorationSlot = "sky" | "ground" | "seat" | "water" | "storage" | "path" | "light" | "forest";

export type DecorationUnlock =
  | { type: "default" }
  | { type: "tier"; id: ProgressionTierId }
  | { type: "questClaimed"; id: string }
  | { type: "achievementUnlocked"; id: string }
  | { type: "goldenLeaf"; value: string }
  | { type: "prestiges"; value: number };

export type DecorationConfigItem = {
  id: string;
  slot: DecorationSlot;
  tier: ProgressionTierId;
  name: string;
  description: string;
  flavorLine: string;
  icon: string;
  visualClass: string;
  unlock: DecorationUnlock;
};

export const DecorationConfig = {
  decorations: [
    {
      id: "sunny_yard",
      slot: "sky",
      tier: "yard",
      name: "햇살 마당",
      description: "첫 화면의 따뜻한 햇살을 유지합니다.",
      flavorLine: "모모가 햇빛이 좋은 자리를 먼저 차지합니다.",
      icon: "sun",
      visualClass: "decor-sunny-yard",
      unlock: { type: "default" },
    },
    {
      id: "orange_basket_corner",
      slot: "storage",
      tier: "yard",
      name: "귤 바구니 코너",
      description: "자동 생산이 시작된 흔적을 마당에 남깁니다.",
      flavorLine: "비어 있던 구석에 첫 바구니가 놓였습니다.",
      icon: "basket",
      visualClass: "decor-basket-corner",
      unlock: { type: "questClaimed", id: "welcome_first_basket" },
    },
    {
      id: "soft_paw_stamp",
      slot: "ground",
      tier: "yard",
      name: "앞발 도장길",
      description: "터치 성장의 시작을 바닥 패턴으로 보여줍니다.",
      flavorLine: "작은 앞발 자국이 귤길을 따라 이어집니다.",
      icon: "paw",
      visualClass: "decor-paw-stamp",
      unlock: { type: "achievementUnlocked", id: "soft_paw_1" },
    },
    {
      id: "nap_mat_set",
      slot: "seat",
      tier: "yard",
      name: "낮잠 평상 세트",
      description: "쉬어 가는 시설이 실제 장면에 보이게 합니다.",
      flavorLine: "포도가 평상 끝에서 살짝 졸고 있습니다.",
      icon: "mat",
      visualClass: "decor-nap-mat",
      unlock: { type: "questClaimed", id: "yard_nap_mat" },
    },
    {
      id: "watering_rill",
      slot: "water",
      tier: "yard",
      name: "작은 물길",
      description: "마당에서 창고로 넘어가는 물길 장식입니다.",
      flavorLine: "물길 옆 귤나무가 천천히 열매를 맺습니다.",
      icon: "water_path",
      visualClass: "decor-watering-rill",
      unlock: { type: "questClaimed", id: "yard_water_path" },
    },
    {
      id: "storehouse_sign",
      slot: "storage",
      tier: "storehouse",
      name: "창고 이름표",
      description: "귤 창고가 열렸다는 첫 시각 신호입니다.",
      flavorLine: "나린이 삐뚤어진 글씨를 다시 고쳐 붙였습니다.",
      icon: "key",
      visualClass: "decor-storehouse-sign",
      unlock: { type: "questClaimed", id: "storehouse_open" },
    },
    {
      id: "crate_lane",
      slot: "path",
      tier: "storehouse",
      name: "상자 운반길",
      description: "창고 시설의 동선을 화면 아래쪽에 만듭니다.",
      flavorLine: "상자가 지나간 자리에 귤 향이 남습니다.",
      icon: "crate",
      visualClass: "decor-crate-lane",
      unlock: { type: "questClaimed", id: "storehouse_crate_line" },
    },
    {
      id: "fragrance_shelf",
      slot: "storage",
      tier: "storehouse",
      name: "향기 선반",
      description: "창고 중반 목표를 향기로운 선반으로 기록합니다.",
      flavorLine: "선반마다 다른 귤 향이 조용히 섞입니다.",
      icon: "shelf",
      visualClass: "decor-fragrance-shelf",
      unlock: { type: "questClaimed", id: "storehouse_25k" },
    },
    {
      id: "cart_stop_flag",
      slot: "path",
      tier: "storehouse",
      name: "수레 정류장 깃발",
      description: "온천으로 이어지는 운반 목표를 보여줍니다.",
      flavorLine: "비로가 깃발이 잘 보이는지 세 번 확인했습니다.",
      icon: "cart_stop",
      visualClass: "decor-cart-stop",
      unlock: { type: "questClaimed", id: "storehouse_cart_stop" },
    },
    {
      id: "onsen_mist",
      slot: "sky",
      tier: "onsen",
      name: "온천 김",
      description: "중반 구간의 공기를 따뜻하게 바꿉니다.",
      flavorLine: "다미가 김이 너무 뜨겁지 않은지 살핍니다.",
      icon: "steam",
      visualClass: "decor-onsen-mist",
      unlock: { type: "questClaimed", id: "onsen_open" },
    },
    {
      id: "warm_pond_stones",
      slot: "water",
      tier: "onsen",
      name: "온천 돌담",
      description: "따뜻한 온천 시설을 홈 화면 장면에 고정합니다.",
      flavorLine: "돌 사이로 작은 귤잎이 떠다닙니다.",
      icon: "pond",
      visualClass: "decor-pond-stones",
      unlock: { type: "questClaimed", id: "onsen_warm_pond" },
    },
    {
      id: "towel_rack_corner",
      slot: "seat",
      tier: "onsen",
      name: "수건걸이 코너",
      description: "휴식 회전율을 담당하는 시설을 시각화합니다.",
      flavorLine: "따뜻한 수건이 차례대로 접혀 있습니다.",
      icon: "steam_towel",
      visualClass: "decor-towel-rack",
      unlock: { type: "questClaimed", id: "onsen_towel_rack" },
    },
    {
      id: "snack_counter_table",
      slot: "storage",
      tier: "onsen",
      name: "귤 간식대",
      description: "소다의 간식 연구가 보이는 장식입니다.",
      flavorLine: "작은 접시마다 다른 모양의 귤조각이 있습니다.",
      icon: "snack",
      visualClass: "decor-snack-counter",
      unlock: { type: "questClaimed", id: "onsen_snack_counter" },
    },
    {
      id: "bamboo_gate",
      slot: "path",
      tier: "bamboo_garden",
      name: "대나무 문",
      description: "후반 구간 진입을 큰 문으로 표시합니다.",
      flavorLine: "대나무 사이로 수레가 지나갈 폭만큼 길이 났습니다.",
      icon: "bamboo",
      visualClass: "decor-bamboo-gate",
      unlock: { type: "questClaimed", id: "bamboo_open" },
    },
    {
      id: "bamboo_cart_track",
      slot: "ground",
      tier: "bamboo_garden",
      name: "카트 바퀴길",
      description: "운반 루트가 넓어지는 느낌을 더합니다.",
      flavorLine: "비로의 카트가 지나가며 규칙적인 선을 남겼습니다.",
      icon: "bamboo_cart",
      visualClass: "decor-cart-track",
      unlock: { type: "questClaimed", id: "bamboo_cart" },
    },
    {
      id: "wind_chime_bridge",
      slot: "light",
      tier: "bamboo_garden",
      name: "바람종 다리",
      description: "소리로 길을 안내하는 후반 장식입니다.",
      flavorLine: "바람이 지나가면 귤 상자의 방향이 정해집니다.",
      icon: "chime",
      visualClass: "decor-wind-chime",
      unlock: { type: "questClaimed", id: "bamboo_wind_bridge" },
    },
    {
      id: "orange_lanterns",
      slot: "light",
      tier: "bamboo_garden",
      name: "귤 등불",
      description: "상점과 축제 느낌을 장면 전체에 더합니다.",
      flavorLine: "루루가 등불 간격을 한 뼘씩 맞췄습니다.",
      icon: "lantern",
      visualClass: "decor-orange-lanterns",
      unlock: { type: "questClaimed", id: "bamboo_lantern" },
    },
    {
      id: "festival_ribbon",
      slot: "sky",
      tier: "bamboo_garden",
      name: "수확 축제 리본",
      description: "광고 mock 보상 흐름을 장식으로 남깁니다.",
      flavorLine: "실제 광고가 아니라도 축제 분위기는 충분합니다.",
      icon: "festival",
      visualClass: "decor-festival-ribbon",
      unlock: { type: "questClaimed", id: "release_ad_festival" },
    },
    {
      id: "golden_forest_arch",
      slot: "forest",
      tier: "golden_forest",
      name: "황금 숲 아치",
      description: "첫 환생 전 목표가 되는 황금 숲 입구입니다.",
      flavorLine: "하늘이 아치 아래 잎새를 조용히 정리합니다.",
      icon: "gold_path",
      visualClass: "decor-golden-arch",
      unlock: { type: "questClaimed", id: "golden_open" },
    },
    {
      id: "first_leaf_plaque",
      slot: "storage",
      tier: "golden_forest",
      name: "첫 황금잎 표본",
      description: "환생 보상이 단순 숫자로 끝나지 않도록 남깁니다.",
      flavorLine: "첫 잎새는 작지만 다음 계절을 여는 무게가 있습니다.",
      icon: "leaf",
      visualClass: "decor-leaf-plaque",
      unlock: { type: "achievementUnlocked", id: "first_leaf" },
    },
    {
      id: "golden_leaf_path",
      slot: "path",
      tier: "golden_forest",
      name: "황금잎 산책길",
      description: "환생 후 자동 생산 회복을 장면으로 보여줍니다.",
      flavorLine: "지난 계절의 발자국이 잎빛 길로 이어집니다.",
      icon: "leaf_polish",
      visualClass: "decor-leaf-path",
      unlock: { type: "questClaimed", id: "golden_leaf_path" },
    },
    {
      id: "compost_greenhouse",
      slot: "forest",
      tier: "golden_forest",
      name: "잎새 퇴비 온실",
      description: "반복 환생의 장기 성장을 시각화합니다.",
      flavorLine: "낡은 잎새가 새 귤나무의 뿌리를 덮습니다.",
      icon: "compost",
      visualClass: "decor-compost-greenhouse",
      unlock: { type: "questClaimed", id: "golden_compost" },
    },
    {
      id: "moon_observatory",
      slot: "sky",
      tier: "golden_forest",
      name: "달귤 관측 하늘",
      description: "최후반 목표를 밤하늘 장면으로 남깁니다.",
      flavorLine: "달빛이 좋은 밤에는 귤 향도 더 선명합니다.",
      icon: "observatory",
      visualClass: "decor-moon-observatory",
      unlock: { type: "questClaimed", id: "golden_observatory" },
    },
    {
      id: "memory_gate_halo",
      slot: "forest",
      tier: "golden_forest",
      name: "계절 기억문 후광",
      description: "현재 RC의 긴 최종 목표를 상징합니다.",
      flavorLine: "모든 계절의 귤빛이 문 안에서 천천히 돌아갑니다.",
      icon: "memory_gate",
      visualClass: "decor-memory-gate",
      unlock: { type: "questClaimed", id: "golden_memory_gate" },
    },
    {
      id: "release_stamp_board",
      slot: "storage",
      tier: "golden_forest",
      name: "출시 점검 보드",
      description: "상점, 광고, 저장 흐름을 확인한 기록입니다.",
      flavorLine: "정원 운영 후보 도장이 아직 마르지 않았습니다.",
      icon: "release",
      visualClass: "decor-release-board",
      unlock: { type: "questClaimed", id: "release_export_ready" },
    },
  ],
} as const satisfies { decorations: DecorationConfigItem[] };

export type DecorationId = (typeof DecorationConfig.decorations)[number]["id"];
