import { ProgressionTierId } from "./ProgressionConfig";

export type QuestChapter = "welcome" | "yard" | "storehouse" | "onsen" | "bamboo" | "golden" | "release";

export type QuestCondition =
  | { type: "totalOranges"; value: string }
  | { type: "totalTaps"; value: number }
  | { type: "upgradeLevel"; id: string; level: number }
  | { type: "generatorLevel"; id: string; level: number }
  | { type: "totalUpgradeLevels"; value: number }
  | { type: "totalGeneratorLevels"; value: number }
  | { type: "eps"; value: string }
  | { type: "goldenLeaf"; value: string }
  | { type: "prestiges"; value: number }
  | { type: "achievementUnlocked"; id: string }
  | { type: "questClaimed"; id: string }
  | { type: "adBoostActive" }
  | { type: "purchasedProducts"; value: number };

export type QuestReward = {
  oranges: string;
  friendship: number;
};

export type QuestConfigItem = {
  id: string;
  chapter: QuestChapter;
  tier: ProgressionTierId;
  order: number;
  title: string;
  instruction: string;
  helperLine: string;
  completionLine: string;
  icon: string;
  capybaraId: string;
  condition: QuestCondition;
  reward: QuestReward;
};

export const QuestConfig = {
  quests: [
    {
      id: "welcome_first_orange",
      chapter: "welcome",
      tier: "yard",
      order: 10,
      title: "첫 귤 건네기",
      instruction: "카피바라에게 귤을 1번 건넵니다.",
      helperLine: "큰 설명보다 한 번의 터치가 정원을 시작합니다.",
      completionLine: "모모가 귤 향을 기억했어요.",
      icon: "orange",
      capybaraId: "momo",
      condition: { type: "totalTaps", value: 1 },
      reward: { oranges: "12", friendship: 3 },
    },
    {
      id: "welcome_soft_paw",
      chapter: "welcome",
      tier: "yard",
      order: 20,
      title: "말랑 앞발 마련",
      instruction: "말랑 앞발을 1레벨로 올립니다.",
      helperLine: "초반 손맛은 터치 업그레이드에서 바로 느껴져야 합니다.",
      completionLine: "앞발 도장이 첫 장에 찍혔어요.",
      icon: "paw",
      capybaraId: "momo",
      condition: { type: "upgradeLevel", id: "soft_paw", level: 1 },
      reward: { oranges: "40", friendship: 4 },
    },
    {
      id: "welcome_first_basket",
      chapter: "welcome",
      tier: "yard",
      order: 30,
      title: "자동 바구니 놓기",
      instruction: "귤 바구니를 1레벨로 올립니다.",
      helperLine: "방치형 게임의 핵심은 손을 떼도 숫자가 오르는 순간입니다.",
      completionLine: "바구니가 혼자 첫 귤을 모았어요.",
      icon: "basket",
      capybaraId: "podo",
      condition: { type: "generatorLevel", id: "orange_basket", level: 1 },
      reward: { oranges: "90", friendship: 4 },
    },
    {
      id: "welcome_steady_ten",
      chapter: "welcome",
      tier: "yard",
      order: 40,
      title: "손끝 리듬 만들기",
      instruction: "카피바라를 10번 터치합니다.",
      helperLine: "짧은 터치가 곧 정원의 박자가 됩니다.",
      completionLine: "작은 박자가 마당에 퍼졌어요.",
      icon: "tap",
      capybaraId: "momo",
      condition: { type: "totalTaps", value: 10 },
      reward: { oranges: "120", friendship: 3 },
    },
    {
      id: "yard_first_100",
      chapter: "yard",
      tier: "yard",
      order: 50,
      title: "작은 바구니 채우기",
      instruction: "누적 100귤을 모읍니다.",
      helperLine: "첫 100귤은 업그레이드와 생산 시설이 같이 굴러간다는 증거입니다.",
      completionLine: "마당 바구니가 가득 찼어요.",
      icon: "basket_1",
      capybaraId: "podo",
      condition: { type: "totalOranges", value: "100" },
      reward: { oranges: "160", friendship: 3 },
    },
    {
      id: "yard_nap_mat",
      chapter: "yard",
      tier: "yard",
      order: 60,
      title: "낮잠 평상 준비",
      instruction: "낮잠 평상을 1레벨로 올립니다.",
      helperLine: "쉬는 공간은 idle 수익이 지루하지 않게 보이는 장치입니다.",
      completionLine: "포도가 평상에서 고개를 끄덕였어요.",
      icon: "mat",
      capybaraId: "podo",
      condition: { type: "generatorLevel", id: "nap_mat", level: 1 },
      reward: { oranges: "240", friendship: 4 },
    },
    {
      id: "yard_parasol",
      chapter: "yard",
      tier: "yard",
      order: 70,
      title: "그늘 자리 만들기",
      instruction: "그늘 파라솔을 1레벨로 올립니다.",
      helperLine: "마당이 넓어질수록 시설의 역할이 눈에 띄어야 합니다.",
      completionLine: "햇살 아래 쉬는 자리가 생겼어요.",
      icon: "parasol",
      capybaraId: "momo",
      condition: { type: "generatorLevel", id: "shade_parasol", level: 1 },
      reward: { oranges: "360", friendship: 4 },
    },
    {
      id: "yard_spoon",
      chapter: "yard",
      tier: "yard",
      order: 80,
      title: "귤 스푼 찾기",
      instruction: "귤 스푼을 1레벨로 올립니다.",
      helperLine: "수동 플레이도 중반까지 의미가 남도록 초반부터 기반을 다집니다.",
      completionLine: "흘리는 귤조각이 줄었어요.",
      icon: "spoon",
      capybaraId: "soda",
      condition: { type: "upgradeLevel", id: "orange_spoon", level: 1 },
      reward: { oranges: "520", friendship: 4 },
    },
    {
      id: "yard_water_path",
      chapter: "yard",
      tier: "yard",
      order: 90,
      title: "작은 물길 열기",
      instruction: "작은 물길을 1레벨로 올립니다.",
      helperLine: "다음 성장 구간으로 넘어가기 전 마당의 생산 루프를 완성합니다.",
      completionLine: "물길 옆 귤나무가 첫 열매를 맺었어요.",
      icon: "water_path",
      capybaraId: "dami",
      condition: { type: "generatorLevel", id: "tiny_watering_path", level: 1 },
      reward: { oranges: "800", friendship: 5 },
    },
    {
      id: "yard_one_thousand",
      chapter: "yard",
      tier: "yard",
      order: 100,
      title: "천 귤 표지판",
      instruction: "누적 1,000귤을 모읍니다.",
      helperLine: "첫 번째 뚜렷한 목표선입니다. 여기부터 창고 준비가 시작됩니다.",
      completionLine: "마당 입구에 천 귤 표지판이 섰어요.",
      icon: "orange_1k",
      capybaraId: "narin",
      condition: { type: "totalOranges", value: "1000" },
      reward: { oranges: "1200", friendship: 5 },
    },
    {
      id: "yard_tap_100",
      chapter: "yard",
      tier: "yard",
      order: 110,
      title: "마당 단골 되기",
      instruction: "카피바라를 100번 터치합니다.",
      helperLine: "누르는 과정 자체가 심심하면 클리커는 오래 가지 않습니다.",
      completionLine: "카피바라들이 집사의 손길을 알아봅니다.",
      icon: "tap_100",
      capybaraId: "momo",
      condition: { type: "totalTaps", value: 100 },
      reward: { oranges: "1500", friendship: 5 },
    },
    {
      id: "storehouse_open",
      chapter: "storehouse",
      tier: "storehouse",
      order: 120,
      title: "귤 창고 문 열기",
      instruction: "누적 5,000귤을 모읍니다.",
      helperLine: "창고는 초반 터치 중심에서 시설 중심으로 넘어가는 첫 전환점입니다.",
      completionLine: "나린이 창고 열쇠를 걸어 두었어요.",
      icon: "key",
      capybaraId: "narin",
      condition: { type: "totalOranges", value: "5000" },
      reward: { oranges: "3200", friendship: 6 },
    },
    {
      id: "storehouse_crate_line",
      chapter: "storehouse",
      tier: "storehouse",
      order: 130,
      title: "나무 상자 줄 맞추기",
      instruction: "나무 상자 줄을 1레벨로 올립니다.",
      helperLine: "창고부터는 시설 이름만 보아도 장면이 떠올라야 합니다.",
      completionLine: "나린이 상자마다 번호표를 붙였어요.",
      icon: "crate",
      capybaraId: "narin",
      condition: { type: "generatorLevel", id: "wooden_crate_line", level: 1 },
      reward: { oranges: "5200", friendship: 6 },
    },
    {
      id: "storehouse_rhythm",
      chapter: "storehouse",
      tier: "storehouse",
      order: 140,
      title: "분류 리듬 익히기",
      instruction: "분류 리듬을 1레벨로 올립니다.",
      helperLine: "수동 터치가 창고 박자와 맞물리는 구간입니다.",
      completionLine: "창고 벽에 박자표가 붙었어요.",
      icon: "metronome",
      capybaraId: "narin",
      condition: { type: "upgradeLevel", id: "sorting_rhythm", level: 1 },
      reward: { oranges: "7400", friendship: 6 },
    },
    {
      id: "storehouse_fragrance",
      chapter: "storehouse",
      tier: "storehouse",
      order: 150,
      title: "향기 창고 채우기",
      instruction: "향기 창고를 1레벨로 올립니다.",
      helperLine: "두 번째 창고 시설은 EPS 숫자를 확실히 끌어올려야 합니다.",
      completionLine: "창고 문틈으로 귤 향이 먼저 나왔어요.",
      icon: "storehouse",
      capybaraId: "narin",
      condition: { type: "generatorLevel", id: "fragrance_storehouse", level: 1 },
      reward: { oranges: "9800", friendship: 7 },
    },
    {
      id: "storehouse_25k",
      chapter: "storehouse",
      tier: "storehouse",
      order: 160,
      title: "향기로운 선반",
      instruction: "누적 25,000귤을 모읍니다.",
      helperLine: "25,000귤은 온천 구간으로 넘어가기 전 목표감을 줍니다.",
      completionLine: "선반마다 작은 이름표가 붙었어요.",
      icon: "shelf",
      capybaraId: "narin",
      condition: { type: "totalOranges", value: "25000" },
      reward: { oranges: "16000", friendship: 7 },
    },
    {
      id: "storehouse_sorting_table",
      chapter: "storehouse",
      tier: "storehouse",
      order: 170,
      title: "분류대 가동",
      instruction: "귤 분류대를 1레벨로 올립니다.",
      helperLine: "전체 생산 배율이 붙는 시설은 구매 의미가 바로 읽혀야 합니다.",
      completionLine: "큰 귤과 작은 귤의 길이 나뉘었어요.",
      icon: "table",
      capybaraId: "narin",
      condition: { type: "generatorLevel", id: "sorting_table", level: 1 },
      reward: { oranges: "22000", friendship: 7 },
    },
    {
      id: "storehouse_cart_stop",
      chapter: "storehouse",
      tier: "storehouse",
      order: 180,
      title: "수레 정류장 세우기",
      instruction: "수레 정류장을 1레벨로 올립니다.",
      helperLine: "창고 후반의 목적지는 온천 진입입니다.",
      completionLine: "수레가 멈추는 자리가 정해졌어요.",
      icon: "cart_stop",
      capybaraId: "biro",
      condition: { type: "generatorLevel", id: "cart_stop", level: 1 },
      reward: { oranges: "30000", friendship: 8 },
    },
    {
      id: "storehouse_total_levels",
      chapter: "storehouse",
      tier: "storehouse",
      order: 190,
      title: "창고 운영표 작성",
      instruction: "자동 생산 시설 총 레벨 20을 달성합니다.",
      helperLine: "한 시설만 누르지 않고 여러 생산 라인을 키우도록 유도합니다.",
      completionLine: "창고 운영표 첫 장이 완성됐어요.",
      icon: "schedule",
      capybaraId: "narin",
      condition: { type: "totalGeneratorLevels", value: 20 },
      reward: { oranges: "42000", friendship: 8 },
    },
    {
      id: "onsen_open",
      chapter: "onsen",
      tier: "onsen",
      order: 200,
      title: "온천 초대장 받기",
      instruction: "누적 75,000귤을 모읍니다.",
      helperLine: "온천은 휴식과 생산이 동시에 보이는 중반 테마입니다.",
      completionLine: "다미가 온천 초대장을 건넸어요.",
      icon: "steam",
      capybaraId: "dami",
      condition: { type: "totalOranges", value: "75000" },
      reward: { oranges: "58000", friendship: 9 },
    },
    {
      id: "onsen_warm_pond",
      chapter: "onsen",
      tier: "onsen",
      order: 210,
      title: "따뜻한 온천 데우기",
      instruction: "따뜻한 온천을 1레벨로 올립니다.",
      helperLine: "새 구간 첫 시설은 화면 분위기와 숫자 성장을 같이 바꿉니다.",
      completionLine: "온천 물결이 잔잔하게 빛났어요.",
      icon: "pond",
      capybaraId: "dami",
      condition: { type: "generatorLevel", id: "warm_pond", level: 1 },
      reward: { oranges: "82000", friendship: 9 },
    },
    {
      id: "onsen_towel_touch",
      chapter: "onsen",
      tier: "onsen",
      order: 220,
      title: "온천 수건 건네기",
      instruction: "온천 수건을 1레벨로 올립니다.",
      helperLine: "중반에도 터치 보상이 밀리지 않게 잡는 퀘스트입니다.",
      completionLine: "따뜻한 수건이 작은 박수를 받았어요.",
      icon: "towel",
      capybaraId: "dami",
      condition: { type: "upgradeLevel", id: "warm_towel", level: 1 },
      reward: { oranges: "110000", friendship: 9 },
    },
    {
      id: "onsen_towel_rack",
      chapter: "onsen",
      tier: "onsen",
      order: 230,
      title: "수건걸이 정리",
      instruction: "김나는 수건걸이를 1레벨로 올립니다.",
      helperLine: "배율 시설을 섞어 구매 선택이 단순하지 않게 만듭니다.",
      completionLine: "수건에서 따뜻한 김이 피어올랐어요.",
      icon: "steam_towel",
      capybaraId: "dami",
      condition: { type: "generatorLevel", id: "steam_towel_rack", level: 1 },
      reward: { oranges: "150000", friendship: 10 },
    },
    {
      id: "onsen_snack_recipe",
      chapter: "onsen",
      tier: "onsen",
      order: 240,
      title: "귤 간식 연구",
      instruction: "귤 간식 레시피를 1레벨로 올립니다.",
      helperLine: "소다의 역할을 직접 성장 목표와 연결합니다.",
      completionLine: "소다가 새 간식 이름을 작게 적었어요.",
      icon: "recipe",
      capybaraId: "soda",
      condition: { type: "upgradeLevel", id: "citrus_recipe", level: 1 },
      reward: { oranges: "190000", friendship: 10 },
    },
    {
      id: "onsen_snack_counter",
      chapter: "onsen",
      tier: "onsen",
      order: 250,
      title: "간식대 차리기",
      instruction: "귤 간식대를 1레벨로 올립니다.",
      helperLine: "휴식 후 복귀 동선을 보상감 있는 시설로 보여줍니다.",
      completionLine: "쉬는 시간 간식 접시가 채워졌어요.",
      icon: "snack",
      capybaraId: "soda",
      condition: { type: "generatorLevel", id: "snack_counter", level: 1 },
      reward: { oranges: "260000", friendship: 11 },
    },
    {
      id: "onsen_eps_1k",
      chapter: "onsen",
      tier: "onsen",
      order: 260,
      title: "천 귤 흐름 만들기",
      instruction: "초당 1,000귤 생산에 도달합니다.",
      helperLine: "숫자 성장의 체감선을 명확히 찍어 줍니다.",
      completionLine: "초당 수익 표시가 빠르게 움직이기 시작했어요.",
      icon: "eps_1k",
      capybaraId: "dami",
      condition: { type: "eps", value: "1000" },
      reward: { oranges: "360000", friendship: 11 },
    },
    {
      id: "onsen_300k",
      chapter: "onsen",
      tier: "onsen",
      order: 270,
      title: "따뜻한 오후",
      instruction: "누적 300,000귤을 모읍니다.",
      helperLine: "대나무 정원으로 넘어가기 전 마지막 중반 확인선입니다.",
      completionLine: "정원에 따뜻한 오후가 찾아왔어요.",
      icon: "afternoon",
      capybaraId: "dami",
      condition: { type: "totalOranges", value: "300000" },
      reward: { oranges: "420000", friendship: 12 },
    },
    {
      id: "bamboo_open",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 280,
      title: "대나무 정원 진입",
      instruction: "누적 1,200,000귤을 모읍니다.",
      helperLine: "후반 첫 장면은 운반 루트가 커진다는 인상을 줘야 합니다.",
      completionLine: "대나무 길 끝에 수레가 기다립니다.",
      icon: "bamboo",
      capybaraId: "biro",
      condition: { type: "totalOranges", value: "1200000" },
      reward: { oranges: "900000", friendship: 13 },
    },
    {
      id: "bamboo_touch",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 290,
      title: "대나무 손길 익히기",
      instruction: "대나무 손길을 1레벨로 올립니다.",
      helperLine: "후반에도 직접 누르는 즐거움이 사라지지 않게 합니다.",
      completionLine: "대나무 사이로 귤이 빠르게 건너갔어요.",
      icon: "bamboo",
      capybaraId: "biro",
      condition: { type: "upgradeLevel", id: "bamboo_touch", level: 1 },
      reward: { oranges: "1300000", friendship: 13 },
    },
    {
      id: "bamboo_cart",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 300,
      title: "대나무 카트 첫 운행",
      instruction: "대나무 카트를 1레벨로 올립니다.",
      helperLine: "대표 시설은 퀘스트에서도 다시 강조합니다.",
      completionLine: "비로가 수레 바퀴를 한번 더 닦았어요.",
      icon: "bamboo_cart",
      capybaraId: "biro",
      condition: { type: "generatorLevel", id: "bamboo_cart", level: 1 },
      reward: { oranges: "1700000", friendship: 14 },
    },
    {
      id: "bamboo_wind_bridge",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 310,
      title: "바람종 다리 연결",
      instruction: "바람종 다리를 1레벨로 올립니다.",
      helperLine: "소리와 동선이 결합된 후반 시설입니다.",
      completionLine: "바람종 소리가 길을 알려 줬어요.",
      icon: "chime",
      capybaraId: "biro",
      condition: { type: "generatorLevel", id: "wind_chime_bridge", level: 1 },
      reward: { oranges: "2400000", friendship: 14 },
    },
    {
      id: "bamboo_festival_clap",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 320,
      title: "축제 박자 맞추기",
      instruction: "축제 박수를 1레벨로 올립니다.",
      helperLine: "수확 축제 버프와 어울리는 손맛 목표입니다.",
      completionLine: "루루가 작은 깃발을 흔들었어요.",
      icon: "clap",
      capybaraId: "ruru",
      condition: { type: "upgradeLevel", id: "festival_clap", level: 1 },
      reward: { oranges: "3200000", friendship: 15 },
    },
    {
      id: "bamboo_lantern",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 330,
      title: "귤 등불길 밝히기",
      instruction: "귤 등불길을 1레벨로 올립니다.",
      helperLine: "저녁 장면이 열리면 정원이 실제 장소처럼 느껴집니다.",
      completionLine: "밤에도 귤빛이 꺼지지 않았어요.",
      icon: "lantern",
      capybaraId: "ruru",
      condition: { type: "generatorLevel", id: "orange_lantern_road", level: 1 },
      reward: { oranges: "4600000", friendship: 15 },
    },
    {
      id: "bamboo_toolbox",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 340,
      title: "집사 도구함 점검",
      instruction: "집사 도구함을 1레벨로 올립니다.",
      helperLine: "전체 배율 시설은 장기 플레이의 핵심 구매가 됩니다.",
      completionLine: "정원 도구가 모두 제자리를 찾았어요.",
      icon: "toolbox",
      capybaraId: "ruru",
      condition: { type: "generatorLevel", id: "butler_toolbox", level: 1 },
      reward: { oranges: "6200000", friendship: 16 },
    },
    {
      id: "bamboo_eps_100k",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 350,
      title: "대나무 급류",
      instruction: "초당 100,000귤 생산에 도달합니다.",
      helperLine: "후반 수익 표시가 단순히 큰 숫자가 아니라 큰 흐름처럼 보이게 합니다.",
      completionLine: "대나무 길의 수레가 쉬지 않고 움직였어요.",
      icon: "eps_100k",
      capybaraId: "biro",
      condition: { type: "eps", value: "100000" },
      reward: { oranges: "9000000", friendship: 16 },
    },
    {
      id: "bamboo_total_levels",
      chapter: "bamboo",
      tier: "bamboo_garden",
      order: 360,
      title: "정원 운영표 확장",
      instruction: "자동 생산 시설 총 레벨 120을 달성합니다.",
      helperLine: "넓어진 정원은 여러 시설 레벨을 함께 요구합니다.",
      completionLine: "운영표가 촘촘한 귤빛으로 채워졌어요.",
      icon: "schedule",
      capybaraId: "biro",
      condition: { type: "totalGeneratorLevels", value: 120 },
      reward: { oranges: "11000000", friendship: 17 },
    },
    {
      id: "golden_open",
      chapter: "golden",
      tier: "golden_forest",
      order: 370,
      title: "황금 숲 입구 보기",
      instruction: "누적 25,000,000귤을 모읍니다.",
      helperLine: "첫 환생 전 목표가 화면에서 분명해야 합니다.",
      completionLine: "하늘이 황금 숲 입구에서 기다립니다.",
      icon: "gold_path",
      capybaraId: "hanul",
      condition: { type: "totalOranges", value: "25000000" },
      reward: { oranges: "18000000", friendship: 18 },
    },
    {
      id: "golden_first_prestige",
      chapter: "golden",
      tier: "golden_forest",
      order: 380,
      title: "첫 계절 넘기기",
      instruction: "환생을 1회 진행합니다.",
      helperLine: "환생은 초기화가 아니라 다음 계절을 여는 의미로 보여야 합니다.",
      completionLine: "첫 황금잎이 정원 앨범에 꽂혔어요.",
      icon: "prestige",
      capybaraId: "hanul",
      condition: { type: "prestiges", value: 1 },
      reward: { oranges: "26000000", friendship: 20 },
    },
    {
      id: "golden_leaf_path",
      chapter: "golden",
      tier: "golden_forest",
      order: 390,
      title: "황금 숲길 걷기",
      instruction: "황금 숲길을 1레벨로 올립니다.",
      helperLine: "환생 후 즉시 새 시설을 확인하는 목표입니다.",
      completionLine: "지난 계절의 빛이 길 위에 남았어요.",
      icon: "gold_path",
      capybaraId: "hanul",
      condition: { type: "generatorLevel", id: "golden_forest_path", level: 1 },
      reward: { oranges: "32000000", friendship: 20 },
    },
    {
      id: "golden_leaf_polish",
      chapter: "golden",
      tier: "golden_forest",
      order: 400,
      title: "황금잎 손질",
      instruction: "황금잎 손질을 1레벨로 올립니다.",
      helperLine: "영구 재화가 터치에도 영향을 준다는 점을 체감시킵니다.",
      completionLine: "황금잎이 손끝에서 조용히 빛났어요.",
      icon: "leaf_polish",
      capybaraId: "hanul",
      condition: { type: "upgradeLevel", id: "golden_leaf_polish", level: 1 },
      reward: { oranges: "36000000", friendship: 20 },
    },
    {
      id: "golden_five_leaves",
      chapter: "golden",
      tier: "golden_forest",
      order: 410,
      title: "다섯 잎새 묶기",
      instruction: "황금 나뭇잎 5개를 보유합니다.",
      helperLine: "반복 환생의 목표가 한 번에 사라지지 않게 중간 목표를 둡니다.",
      completionLine: "하늘이 잎새를 작은 끈으로 묶었어요.",
      icon: "leaf_5",
      capybaraId: "hanul",
      condition: { type: "goldenLeaf", value: "5" },
      reward: { oranges: "42000000", friendship: 22 },
    },
    {
      id: "golden_compost",
      chapter: "golden",
      tier: "golden_forest",
      order: 420,
      title: "잎새 퇴비장 열기",
      instruction: "잎새 퇴비장을 1레벨로 올립니다.",
      helperLine: "후반 시설은 지난 진행이 실제 힘이 된다는 감각을 줍니다.",
      completionLine: "지난 계절의 잎새가 뿌리를 덮었어요.",
      icon: "compost",
      capybaraId: "hanul",
      condition: { type: "generatorLevel", id: "leaf_compost_house", level: 1 },
      reward: { oranges: "52000000", friendship: 22 },
    },
    {
      id: "golden_memory_touch",
      chapter: "golden",
      tier: "golden_forest",
      order: 430,
      title: "기억의 손길",
      instruction: "기억의 집사술을 1레벨로 올립니다.",
      helperLine: "두 번째 환생 이후 수동 플레이의 장기 목표입니다.",
      completionLine: "지난 계절의 집사 노트가 다시 펼쳐졌어요.",
      icon: "memory",
      capybaraId: "hanul",
      condition: { type: "upgradeLevel", id: "memory_butler", level: 1 },
      reward: { oranges: "64000000", friendship: 24 },
    },
    {
      id: "golden_observatory",
      chapter: "golden",
      tier: "golden_forest",
      order: 440,
      title: "달귤 관측",
      instruction: "달귤 관측소를 1레벨로 올립니다.",
      helperLine: "최후반 시설은 다음 환생까지의 기대감을 만들어야 합니다.",
      completionLine: "달빛이 좋은 수확일이 표시됐어요.",
      icon: "observatory",
      capybaraId: "hanul",
      condition: { type: "generatorLevel", id: "moon_orange_observatory", level: 1 },
      reward: { oranges: "78000000", friendship: 24 },
    },
    {
      id: "golden_memory_gate",
      chapter: "golden",
      tier: "golden_forest",
      order: 450,
      title: "계절 기억문 열기",
      instruction: "계절 기억문을 1레벨로 올립니다.",
      helperLine: "현재 RC의 긴 목표를 명확한 최종 장면으로 보여줍니다.",
      completionLine: "모든 계절의 귤빛이 문 안에서 반짝였어요.",
      icon: "memory_gate",
      capybaraId: "hanul",
      condition: { type: "generatorLevel", id: "season_memory_gate", level: 1 },
      reward: { oranges: "98000000", friendship: 28 },
    },
    {
      id: "release_ad_festival",
      chapter: "release",
      tier: "yard",
      order: 460,
      title: "수확 축제 리허설",
      instruction: "귤 수확 축제 mock 보상을 1회 확인합니다.",
      helperLine: "광고 보상은 실제 광고처럼 오해되지 않되 흐름은 검증되어야 합니다.",
      completionLine: "루루가 축제 리본을 걸었어요.",
      icon: "festival",
      capybaraId: "ruru",
      condition: { type: "adBoostActive" },
      reward: { oranges: "5000", friendship: 8 },
    },
    {
      id: "release_shop_gift",
      chapter: "release",
      tier: "storehouse",
      order: 470,
      title: "특별 상자 점검",
      instruction: "mock IAP 상품 보상을 1회 수령합니다.",
      helperLine: "출시 전 결제 흐름은 샌드박스 문구로만 보여야 합니다.",
      completionLine: "상점 점검표에 첫 도장이 찍혔어요.",
      icon: "gift",
      capybaraId: "ruru",
      condition: { type: "purchasedProducts", value: 1 },
      reward: { oranges: "12000", friendship: 8 },
    },
    {
      id: "release_album_first",
      chapter: "release",
      tier: "yard",
      order: 480,
      title: "앨범 첫 장 확인",
      instruction: "첫 귤 인사 업적을 해금합니다.",
      helperLine: "컬렉션은 단순 표가 아니라 플레이 기억을 다시 보여주는 화면입니다.",
      completionLine: "앨범 첫 장이 조심스럽게 열렸어요.",
      icon: "album",
      capybaraId: "momo",
      condition: { type: "achievementUnlocked", id: "first_orange" },
      reward: { oranges: "1000", friendship: 6 },
    },
    {
      id: "release_album_basket",
      chapter: "release",
      tier: "yard",
      order: 490,
      title: "자동 생산 기록 붙이기",
      instruction: "첫 자동 바구니 업적을 해금합니다.",
      helperLine: "업적과 퀘스트가 서로 연결되어 다음 행동을 안내합니다.",
      completionLine: "바구니 기록 사진이 앨범에 붙었어요.",
      icon: "album",
      capybaraId: "podo",
      condition: { type: "achievementUnlocked", id: "basket_1" },
      reward: { oranges: "1600", friendship: 6 },
    },
    {
      id: "release_export_ready",
      chapter: "release",
      tier: "golden_forest",
      order: 500,
      title: "운영 후보 점검",
      instruction: "환생을 3회 진행합니다.",
      helperLine: "release candidate에서는 긴 흐름도 저장과 UI가 무너지지 않아야 합니다.",
      completionLine: "정원 운영 후보 표식이 반짝였어요.",
      icon: "release",
      capybaraId: "hanul",
      condition: { type: "prestiges", value: 3 },
      reward: { oranges: "120000000", friendship: 30 },
    },
  ],
} as const satisfies { quests: QuestConfigItem[] };

export type QuestId = (typeof QuestConfig.quests)[number]["id"];
