import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd();
const sourceIcon = join(root, "src/assets/raster/release/app-icon-candidate.png");
const sourceStoreKey = join(root, "src/assets/raster/release/store-key-visual.png");
const sourceSplashSvg = join(root, "src/assets/generated/release/splash-final.svg");
const outRoot = join(root, "platform-assets");

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function resizePng(source, output, width, height) {
  ensureDir(dirname(output));
  const result = spawnSync("/usr/bin/sips", ["-z", String(height), String(width), source, "--out", output], {
    encoding: "utf8",
  });
  if (result.status !== 0) {
    throw new Error(`sips failed for ${output}\n${result.stdout}\n${result.stderr}`);
  }
}

function copy(source, output) {
  ensureDir(dirname(output));
  copyFileSync(source, output);
}

function writeJson(output, value) {
  ensureDir(dirname(output));
  writeFileSync(output, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeText(output, value) {
  ensureDir(dirname(output));
  writeFileSync(output, value, "utf8");
}

ensureDir(outRoot);
copy(sourceIcon, join(outRoot, "source/app-icon-1024.png"));
copy(sourceStoreKey, join(outRoot, "source/store-key-visual.png"));
copy(sourceSplashSvg, join(outRoot, "source/splash-final.svg"));

const iosIcons = [
  ["iphone", "20x20", "2x", 40],
  ["iphone", "20x20", "3x", 60],
  ["iphone", "29x29", "2x", 58],
  ["iphone", "29x29", "3x", 87],
  ["iphone", "40x40", "2x", 80],
  ["iphone", "40x40", "3x", 120],
  ["iphone", "60x60", "2x", 120],
  ["iphone", "60x60", "3x", 180],
  ["ipad", "20x20", "1x", 20],
  ["ipad", "20x20", "2x", 40],
  ["ipad", "29x29", "1x", 29],
  ["ipad", "29x29", "2x", 58],
  ["ipad", "40x40", "1x", 40],
  ["ipad", "40x40", "2x", 80],
  ["ipad", "76x76", "1x", 76],
  ["ipad", "76x76", "2x", 152],
  ["ipad", "83.5x83.5", "2x", 167],
  ["ios-marketing", "1024x1024", "1x", 1024],
];

const iosAppIconDir = join(outRoot, "ios/AppIcon.appiconset");
const iosImages = iosIcons.map(([idiom, size, scale, pixels]) => {
  const filename = `AppIcon-${size.replace(".", "_")}@${scale}-${idiom}.png`;
  resizePng(sourceIcon, join(iosAppIconDir, filename), pixels, pixels);
  return { idiom, size, scale, filename };
});

writeJson(join(iosAppIconDir, "Contents.json"), {
  images: iosImages,
  info: {
    author: "xcode",
    version: 1,
  },
});

const androidIconSizes = [
  ["mipmap-mdpi", 48, 108],
  ["mipmap-hdpi", 72, 162],
  ["mipmap-xhdpi", 96, 216],
  ["mipmap-xxhdpi", 144, 324],
  ["mipmap-xxxhdpi", 192, 432],
];

for (const [dir, launcherSize, foregroundSize] of androidIconSizes) {
  resizePng(sourceIcon, join(outRoot, `android/res/${dir}/ic_launcher.png`), launcherSize, launcherSize);
  resizePng(sourceIcon, join(outRoot, `android/res/${dir}/ic_launcher_round.png`), launcherSize, launcherSize);
  resizePng(sourceIcon, join(outRoot, `android/res/${dir}/ic_launcher_foreground.png`), foregroundSize, foregroundSize);
}

writeText(join(outRoot, "android/res/values/ic_launcher_background.xml"), `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <color name="ic_launcher_background">#FFF7DC</color>
</resources>
`);

const androidResRoot = join(root, "android/app/src/main/res");
for (const [dir, launcherSize, foregroundSize] of androidIconSizes) {
  resizePng(sourceIcon, join(androidResRoot, `${dir}/ic_launcher.png`), launcherSize, launcherSize);
  resizePng(sourceIcon, join(androidResRoot, `${dir}/ic_launcher_round.png`), launcherSize, launcherSize);
  resizePng(sourceIcon, join(androidResRoot, `${dir}/ic_launcher_foreground.png`), foregroundSize, foregroundSize);
}
writeText(join(androidResRoot, "values/ic_launcher_background.xml"), `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <color name="ic_launcher_background">#FFF7DC</color>
</resources>
`);

const splashTargets = [
  ["portrait-mdpi", 320, 568],
  ["portrait-hdpi", 480, 852],
  ["portrait-xhdpi", 720, 1280],
  ["portrait-xxhdpi", 1080, 1920],
  ["portrait-xxxhdpi", 1440, 2560],
];

for (const [name, width, height] of splashTargets) {
  resizePng(sourceStoreKey, join(outRoot, `splash/${name}.png`), width, height);
}

writeText(join(outRoot, "README.md"), `# Platform Asset Export Candidates

Generated by \`npm run export:assets\`.

These are submission-prep candidates, not proof of App Store / Google Play upload.

- iOS app icon set: \`ios/AppIcon.appiconset/\`
- Android icon candidates: \`android/res/mipmap-*/\`
- Android launcher background: \`android/res/values/ic_launcher_background.xml\`
- Splash candidates: \`splash/portrait-*.png\`
- Source copies: \`source/\`

The Android shell under \`android/app/src/main/res\` is updated with the launcher icon candidates. iOS still requires CocoaPods/Xcode environment before native project generation.
`);

console.info("exported platform asset candidates to platform-assets/");
